# Generated by Django 5.2.12 on 2026-03-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
