# Generated by Django 5.2.12 on 2026-03-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninUser', '0002_remove_user_email_remove_user_username_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
