# Generated by Django 5.2.12 on 2026-03-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninUser', '0003_delete_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='apns_token',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='fcm_token',
        ),
    ]
