# Generated by Django 5.2.12 on 2026-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninUser', '0004_remove_userdevice_apns_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
