# Generated by Django 5.2.12 on 2026-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_connection_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='receiver_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender_archived',
            field=models.BooleanField(default=False),
        ),
    ]
