# Generated by Django 5.2.12 on 2026-04-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
